### ISSUE TITLE
Organize Javascript code in AMD form

### ISSUE THREAD

**Issue by Ravenink** [UNEDLabs/moodle-mod_ejsapp#12]
module.js, external javascript libraries (ace, js-interpreter, blockly...) and the new experiment addon javascript files should be used as AMD modules: https://docs.moodle.org/dev/Javascript_Modules

**Comment by Ravenink** [comment]
Commit 84aaeb57dac8f8860092bef5b3eb72a0c72e4c76 solves this for old YUI module.js javascript code. Now its time to do it with external javascript libraries (if we find that possible/reasonable) and the new experiment addon

**Comment by Ravenink** [comment]
Maybe we could use this: https://github.com/google/blockly-samples/tree/master/examples/blockly-requirejs

**Comment by danielgalanv** [comment]
Closed by 8e0d8fb
