### ISSUE TITLE
Join the navbar and execution bar into one single control bar

### ISSUE THREAD

**Issue by Ravenink** [UNEDLabs/moodle-mod_ejsapp#16]
The bar for adding/deleting/showing experiments, charts, controllers and events code would be better joined with the bar for selecting which of these elements to run in an experiment.

**Comment by danielgalanv** [comment]
Commit 63ba2e5 solves this issue. Navbar and buttons CSS should be tested on different screen sizes and browsers to check that works nice.

**Comment by Ravenink** [comment]
Awesome. I made a couple of tiny changes in CSS and Javascript related to this issue and committed them.

**Comment by danielgalanv** [comment]
The possibility of deselecting scripts to be executed was not contemplated. With commit 9e6cf09 it is possible.

**Comment by Ravenink** [comment]
@danielgalanv Yes, all CSS rules should be in styles.css (look at issue #17)

Can you relocate them? If not, I'll do it.
