### ISSUE TITLE
Improve Blockly view layout and integration

### ISSUE THREAD

**Issue by Ravenink** [UNEDLabs/moodle-mod_ejsapp#9]
Give users the possibility of reordering the layout inside an ejsapp activity in which Blockly is used.

At this moment, the layout is fixed and like this:

-------------------
Text                
-------------------
EjsS Lab | Graphs
-------------------
Blockly-ACE
-------------------
Text 2
-------------------

The idea is that users would be able to move the Blockly editor so that it could be placed upside, on the right or on the left of the Text2, the EjsS Lab, the Graphs or the Text 1.

**Comment by Ravenink** [comment]
@danielgalanv You already did this outside Moodle and worked pretty well. If you could try to make it work well within the EJSApp activity, it would be awesome.

**Comment by danielgalanv** [comment]
Commit 9e6cf09 make this possible. Some css style has been added to renderer.php, we should evaluate if it is necessary to move it to styles.css.

**Comment by Ravenink** [comment]
@danielgalanv This is still working very badly. I insist: if we can't make this work well, just remove the option to resize and relocate the different DIV sections, just like it was till a few days ago; but please don't send commits with the option added and working this poorly.

**Comment by danielgalanv** [comment]
Maybe this is useful:
- Sortable elements without JQuery UI: https://varaa.com/packages/sortable/
- Resizable elements: https://www.codecademy.com/forum_questions/50ccccd3841b2c4d760005e9

**Comment by danielgalanv** [comment]
Closed by 636af86
